import 'package:flutter/material.dart';

import '../data/model/car_model.dart';

const loginScreen = '/loginScreen';
const registerScreen = '/registerScreen';
const carsScreen = 'carsScreen';
const carDetailsScreen = '/carDetailsScreen';
const addCarScreen = '/addCarScreen';

const baseUrl = 'https://eco-mern-api.herokuapp.com/api/';

List<Car> allCars = [
  Car(
    color: 'black',
    id: 1,
    price: '250000\$',
    year: '2000',
    engine: '1600 cc',
    kilometres: '10000 K.M',
    place: 'Alexandria',
    statue: 'used',
    title: 'Mazda',
    description: '',
    image: Image.asset('assets/images/mazda.png'),
  ),
  Car(
    color: 'white',
    id: 2,
    price: '250000\$',
    year: '2000',
    engine: '1600 cc',
    kilometres: '10000 K.M',
    place: 'Alexandria',
    statue: 'used',
    title: 'Toyota',
    description: '',
    image: Image.asset('assets/images/toyota.jpg'),
  ),
  Car(
    color: 'Red',
    id: 3,
    price: '250000\$',
    year: '2000',
    engine: '1600 cc',
    kilometres: '10000 K.M',
    place: 'Alexandria',
    statue: 'used',
    title: 'nissan',
    description: '',
    image: Image.asset('assets/images/nissan.jpg'),
  ),
  Car(
    color: 'Red',
    id: 4,
    price: '250000\$',
    year: '2000',
    engine: '1600 cc',
    kilometres: '10000 K.M',
    place: 'Alexandria',
    statue: 'used',
    title: 'sobaro',
    description: '',
    image: Image.asset('assets/images/sobaro.jpg'),
  ),
  Car(
    color: 'Red',
    id: 5,
    price: '250000\$',
    year: '2000',
    engine: '1600 cc',
    kilometres: '10000 K.M',
    place: 'Alexandria',
    statue: 'used',
    title: 'dihatsu',
    description: '',
    image: Image.asset('assets/images/dihatsu.jpg'),
  ),
  Car(
    color: 'Red',
    id: 6,
    price: '250000\$',
    year: '2000',
    engine: '1600 cc',
    kilometres: '10000 K.M',
    place: 'Alexandria',
    statue: 'used',
    title: 'Toyota',
    description: '',
    image: Image.asset('assets/images/toyota.jpg'),
  ),
  Car(
    color: 'Red',
    id: 7,
    price: '250000\$',
    year: '2000',
    engine: '1600 cc',
    kilometres: '10000 K.M',
    place: 'Alexandria',
    statue: 'used',
    title: 'Mazda',
    description: '',
    image: Image.asset('assets/images/mazda.png'),
  ),
  Car(
    color: 'Red',
    id: 8,
    price: '250000\$',
    year: '2000',
    engine: '1600 cc',
    kilometres: '10000 K.M',
    place: 'Alexandria',
    statue: 'used',
    title: 'nissan',
    description: '',
    image: Image.asset('assets/images/nissan.jpg'),
  ),
  Car(
    color: 'Red',
    id: 9,
    price: '250000\$',
    year: '2000',
    engine: '1600 cc',
    kilometres: '10000 K.M',
    place: 'Alexandria',
    statue: 'used',
    title: 'sobaro',
    description: '',
    image: Image.asset('assets/images/sobaro.jpg'),
  ),
  Car(
    color: 'Red',
    id: 10,
    price: '250000\$',
    year: '2000',
    engine: '1600 cc',
    kilometres: '10000 K.M',
    place: 'Alexandria',
    statue: 'used',
    title: 'dihatsu',
    description: '',
    image: Image.asset('assets/images/dihatsu.jpg'),
  ),
  Car(
    color: 'Red',
    id: 11,
    price: '250000\$',
    year: '2000',
    engine: '1600 cc',
    kilometres: '10000 K.M',
    place: 'Alexandria',
    statue: 'used',
    title: 'Mazda',
    description: '',
    image: Image.asset('assets/images/mazda.png'),
  ),
  Car(
    color: 'Red',
    id: 12,
    price: '250000\$',
    year: '2000',
    engine: '1600 cc',
    kilometres: '10000 K.M',
    place: 'Alexandria',
    statue: 'used',
    title: 'Toyota',
    description: '',
    image: Image.asset('assets/images/toyota.jpg'),
  ),
  Car(
    color: 'Red',
    id: 13,
    price: '250000\$',
    year: '2000',
    engine: '1600 cc',
    kilometres: '10000 K.M',
    place: 'Alexandria',
    statue: 'used',
    title: 'nissan',
    description: '',
    image: Image.asset('assets/images/nissan.jpg'),
  ),
  Car(
    color: 'Red',
    id: 14,
    price: '250000\$',
    year: '2000',
    engine: '1600 cc',
    kilometres: '10000 K.M',
    place: 'Alexandria',
    statue: 'used',
    title: 'Sobaro',
    description: '',
    image: Image.asset('assets/images/sobaro.jpg'),
  ),
  Car(
    color: 'Red',
    id: 15,
    price: '250000\$',
    year: '2000',
    engine: '1600 cc',
    kilometres: '10000 K.M',
    place: 'Alexandria',
    statue: 'used',
    title: 'dihatsu',
    description: '',
    image: Image.asset('assets/images/dihatsu.jpg'),
  ),
  Car(
    color: 'Red',
    id: 16,
    price: '250000\$',
    year: '2000',
    engine: '1600 cc',
    kilometres: '10000 K.M',
    place: 'Alexandria',
    statue: 'used',
    title: 'Toyota',
    description: '',
    image: Image.asset('assets/images/toyota.jpg'),
  ),
  Car(
    color: 'Red',
    id: 17,
    price: '250000\$',
    year: '2000',
    engine: '1600 cc',
    kilometres: '10000 K.M',
    place: 'Alexandria',
    statue: 'used',
    title: 'Mazda',
    description: '',
    image: Image.asset('assets/images/mazda.png'),
  ),
  Car(
    color: 'Red',
    id: 18,
    price: '250000\$',
    year: '2000',
    engine: '1600 cc',
    kilometres: '10000 K.M',
    place: 'Alexandria',
    statue: 'used',
    title: 'nissan',
    description: '',
    image: Image.asset('assets/images/nissan.jpg'),
  ),
  Car(
    color: 'Red',
    id: 19,
    price: '250000\$',
    year: '2000',
    engine: '1600 cc',
    kilometres: '10000 K.M',
    place: 'Alexandria',
    statue: 'used',
    title: 'sobaro',
    description: '',
    image: Image.asset('assets/images/sobaro.jpg'),
  ),
  Car(
    color: 'Red',
    id: 20,
    price: '250000\$',
    year: '2000',
    engine: '1600 cc',
    kilometres: '10000 K.M',
    place: 'Alexandria',
    statue: 'used',
    title: 'Toyota',
    description: '',
    image: Image.asset('assets/images/toyota.jpg'),
  ),
];
